# Generated by Django 5.2.17 on 2026-09-29 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sinif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ad",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Sınıf adı"
                    ),
                ),
                ("sira", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
            ],
            options={
                "verbose_name": "Sınıf",
                "verbose_name_plural": "Sınıflar",
                "ordering": ["sira", "ad"],
            },
        ),
        migrations.CreateModel(
            name="Soru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sira", models.PositiveIntegerField(unique=True, verbose_name="Sıra")),
                ("secenek_a", models.TextField(verbose_name="A seçeneği")),
                ("secenek_b", models.TextField(verbose_name="B seçeneği")),
                (
                    "kisa_a",
                    models.CharField(
                        help_text="Sonuç tablosunda görünür",
                        max_length=200,
                        verbose_name="A kısa metin",
                    ),
                ),
                (
                    "kisa_b",
                    models.CharField(
                        help_text="Sonuç tablosunda görünür",
                        max_length=200,
                        verbose_name="B kısa metin",
                    ),
                ),
                ("aktif", models.BooleanField(default=True, verbose_name="Aktif")),
            ],
            options={
                "verbose_name": "Soru",
                "verbose_name_plural": "Sorular",
                "ordering": ["sira"],
            },
        ),
        migrations.CreateModel(
            name="VeliKodu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kod",
                    models.CharField(max_length=20, unique=True, verbose_name="Kod"),
                ),
                (
                    "olusturma",
                    models.DateTimeField(auto_now_add=True, verbose_name="Oluşturulma"),
                ),
                (
                    "kullanim",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Kullanıldığı tarih"
                    ),
                ),
                (
                    "sinif",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kodlar",
                        to="anket.sinif",
                        verbose_name="Sınıf",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veli kodu",
                "verbose_name_plural": "Veli kodları",
                "ordering": ["sinif__sira", "sinif__ad", "olusturma", "kod"],
            },
        ),
        migrations.CreateModel(
            name="VeliYaniti",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad_soyad", models.CharField(max_length=100, verbose_name="Ad Soyad")),
                (
                    "tarih",
                    models.DateTimeField(auto_now_add=True, verbose_name="Tarih"),
                ),
                (
                    "kod",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="yanit",
                        to="anket.velikodu",
                        verbose_name="Veli kodu",
                    ),
                ),
                (
                    "sinif",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="yanitlar",
                        to="anket.sinif",
                        verbose_name="Sınıf",
                    ),
                ),
            ],
            options={
                "verbose_name": "Veli yanıtı",
                "verbose_name_plural": "Veli yanıtları",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Cevap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "secim",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B")],
                        max_length=1,
                        verbose_name="Seçim",
                    ),
                ),
                (
                    "soru",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cevaplar",
                        to="anket.soru",
                    ),
                ),
                (
                    "yanit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cevaplar",
                        to="anket.veliyaniti",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cevap",
                "verbose_name_plural": "Cevaplar",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("yanit", "soru"), name="yanit_soru_tekil"
                    )
                ],
            },
        ),
    ]
