# Generated by Django 5.2.17 on 2026-09-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("anket", "0002_baslangic_verisi"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="veliyaniti",
            name="kod",
        ),
        migrations.DeleteModel(
            name="VeliKodu",
        ),
    ]
